env:
    MANIFEST: https://github.com/Octavi-Staging/manifest.git -b thirteen
    DEVICE: RMX1901
    OEM: realme
    DT_LINK: https://github.com/shravansayz/device_realme_RMX1901_T.git -b octavi
    DT_PATH: device/realme/RMX1901
    VT_LINK: https://github.com/SlicKker-001/vendor_realme_RMX1901.git  -b 13
    KT_LINK: https://github.com/ashim-anwar/kernel_realme_RMX1901.git -b x.337-KSU
    VT_PATH: vendor/realme/RMX1901
    KT_PATH: kernel/realme/RMX1901
    LUNCH_COMBO: octavi_${DEVICE}-userdebug
    OUTPUT: O*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[!f1d6be2955abc0e707d19e911e742d164c53d4abd3136d5cda5bc0c25a09e9a7f8668ea263e382612f3f8de8f51a6413!]
    URI: https://fleur.shazuxd7.workers.dev/0:/ci/ccache.tar.gz
    ROM_U: 1
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Storage-Checker_script:
      - ./d0wnl0ad

  Sync_script:
      - ./syn0

  Build_script:
      - ./bu1ld

  upload_script:
      - sh upl0ad
