#!/bin/bash

cd ~/work
. build/envsetup.sh
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 120G
ccache -o compression=true
ccache -z
lunch "$LUNCH_COMBO"
$EXTRA_CMD
make bacon -j8 & sleep 90m


