#!/bin/bash
cd ~/work
$EXTRA_CMD
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z
. build/envsetup.sh
lunch "$LUNCH_COMBO"
mka -j31  $TARGET
