#!/bin/bash

cd ~/work
. build/envsetup.sh
$EXTRA_CMD
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 105G
ccache -o compression=true
ccache -z
brunch "$LUNCH_COMBO" & sleep 100m
