#!/bin/bash
df -h
free -h
nproc
cat /etc/os*
env

sudo pacman -S pigz --noconfirm



cd /tmp # Where to download cccahe
time aria2c $URI -x16 -s50
time tar xf ccache.tar.gz
echo 1
echo 1
echo 2
echo

