#!/bin/bash
mkdir -p ~/work
cd ~/work
repo init --depth=1 -u $MANIFEST
repo sync -c --force-sync --no-tags --no-clone-bundle -j8 --optimized-fetch --prune
git clone $DT_LINK $DT_PATH
git clone $VT_LINK $VT_PATH
echo "Sync Done"
echo "Now Build Will Begin"
echo 1
echo 2
echo 3
echo "Lets Go"
