#!/bin/bash


if [ "$ROM_U" == "1" ]; then
cd ~/work/out/target/product/$DEVICE
wget https://github.com/Sushrut1101/GoFile-Upload/raw/master/upload.sh
chmod +x upload.sh
sudo apt install jq -y
./upload.sh P*.zip

fi
