#!/bin/bash
sudo apt install pigz 
cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

mkdir -p ~/.config/rclone
echo "$CLO_1" > ~/.config/rclone/rclone.conf # Write rclone config found from env variable, so that cloud storage can be used to upload ccache
time rclone copy ccache.tar.gz $CLO -P

if [ "$ROM_U" == "1" ]; then
cd ~/work/out/target/product/$DEVICE
curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
cat link.txt && echo " "
fi
